gaconnector.track({
    "gclid": "",
    "lc_source": "(direct)",
    "lc_medium": "(none)",
    "lc_campaign": "(direct)",
    "lc_term": "(not set)",
    "lc_content": "(not set)",
    "lc_landing": "https://www.ironhack.com/en",
    "lc_referrer": "(not set)",
    "lc_channel": "Direct",
    "ip_address": "-",
    "OS": "Windows 10",
    "device": "desktop",
    "browser": "Chrome 106.0.0.0",
    "city": "Hyderabad",
    "country": "Pakistan",
    "country_code": "PK",
    "region": "Sindh",
    "time_zone": "Asia/Karachi",
    "latitude": "25.3924",
    "longitude": "68.3737"
})